<a href="https://colab.research.google.com/github/cantaruttim/Rotinas/blob/main/Lendo_Tabelas_em_Arquivos_PDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tabula-py

Collecting tabula-py
  Downloading tabula_py-2.7.0-py3-none-any.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 23.5 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.5.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.22.4)
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from tabula-py) (1.7.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=0.25.3->tabula-py) (1.16.0)
Installing collected packages: tabula-py
Successfully installed tabula-py-2.7.0

In [2]:
import tabula

In [3]:
## Podemos ver que na página que queremos trabalhar desse documento, temos duas tabelas

lista_tabelas = tabula.read_pdf("https://hospitalangelinacaron.org.br/hac/wp-content/uploads/2022/12/Balanco-Social-2021.pdf", pages='8')
print(len(lista_tabelas))

WARNING:tabula.io:Got stderr: Aug 07, 2023 11:36:02 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (31) in font KHJFJO+Montserrat-Light
Aug 07, 2023 11:36:05 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 31 (.notdef) in font KHJFJO+Montserrat-Light

2

In [4]:
## Podemos visualizar as tabelas
### Obs¹: Ao realizar a leitura, podemos ver que as tabelas estão unificadas (nos mostrando apenas 1 tabela)

for tabela in lista_tabelas:
  display(tabela)

,PASSIVO + PATRIMÔNIO LÍQUIDO,NOTA,Unnamed: 0,Unnamed: 1,SUS- Incentivo - Diárias Extras de UTI,Unnamed: 2,9.959,136.865
0,CIRCULANTE,NaN,73.108.189 41.657.722,NaN,Receitas a Faturar,NaN,6.067.487,0
1,Fornecedores,NaN,12.559.112 9.301.363,NaN,Subvenções Recebidas,NaN,4.848.826,2.994.260
2,Salários e Contribuições Sociais,NaN,15.156.339 11.716.560,NaN,Receitas sem Restrição,28b,93.298.042,62.754.588
3,Obrigações Fiscais,NaN,411.790 1.296.084,NaN,Convênios Assistenciais,NaN,111.246,698.890
4,Outras Obrigações,NaN,1.363.500 1.569.931,NaN,Convênios Privados,NaN,10.305.533,6.011.318
5,Créditos de Clientes,NaN,400.445 472.619,NaN,Pacientes Particulares,NaN,40.976.493,34.420.287
6,NaN,NaN,23.284.719 1.279.161,NaN,Doações Recebidas,NaN,2.282.808,1.927.002
7,Emprestimos e Financiamentos de Ativos,NaN,0 2.651.925,NaN,Remissão de Dividas do PROSUS,NaN,29.284.467,15.008.710
8,Passivo de Arrendamento,NaN,9.106.138 6.596.923,NaN,Receitas Diversas,NaN,10.337.495,4.688.381
9,Receitas Diferidas - Subvenção a Realizar,NaN,10.826.146 6.773.156,NaN,RECEITAS FILIAL CURITIBA,NaN,333.130,173.520
10,NÃOC IRCULANTE,NaN,95.010.439 124.687.325,NaN,Receitas sem Restrição,28b,333.130,173.520
11,Emprestimos e Financiamentos de Ativos,NaN,106.054 106.054,NaN,Convênios Privados,NaN,248.565,151.463
12,NaN,NaN,428.571 300.057,NaN,Pacientes Particulares,NaN,84.565,22.057
13,Passivo de Arrendamento,NaN,0 2.173.487,NaN,DEDUÇÕES DAS RECEITAS,29,-1.034.212,-3.481.921
14,Receitas Diferidas - Subvenções a Realizar,NaN,38.138.139 36.698.692,NaN,(-) Devolução p/ Pacientes,NaN,-7.961,-2.700
15,Provisão Para Contingências,NaN,3.277.226 3.064.119,NaN,(-) Glosas s/ Serviços,NaN,-1.026.251,-3.479.221
16,Dívida Tributária - Prosus - Lei no 12.873/13,NaN,49.196.083 78.480.550,NaN,RECEITA OPERACIONAL LÍQUIDA,NaN,308.213.436,273.567.637
17,Créditos Não Homologados -,NaN,3.864.366 3.864.366,NaN,CUSTOS DOS SERV./PRODUTOS - MATRIZ,30,262.204.797,235.215.933
18,Prosus - Lei no 12.873/13,NaN,NaN,NaN,Custo com Pessoal,NaN,82.167.977,71.082.565
19,PATRIMÔNIO LÍQUIDO,NaN,17.161.647 3.926.972,NaN,Suprimentos,NaN,56.625.339,44.342.432
20,Patrimonio Social,NaN,62.185.996 62.185.996,NaN,Aluguel - Uso Instalações,NaN,6.003.872,59.092
21,Reservas de Contribuição,NaN,816.784 816.784,NaN,NaN,NaN,95.813.647,97.435.610
22,NaN,NaN,-59.016.726 -66.242.530,NaN,Depreciação,NaN,12.231.182,12.769.719
23,Superávit do Exercício,NaN,13.175.593 7.166.722,NaN,Outros Custos,NaN,9.362.780,9.526.515
24,TOTAL PASSIVO + PATRIMÔNIO LÍQUIDO,NaN,185.280.274 170.272.019,NaN,CUSTOS SERV./PROD - FILIAL DE CURITIBA,31,2.464.291,1.913.914
25,NaN,NaN,NaN,NaN,Custo com Pessoal,NaN,832.500,710.176
26,NaN,NaN,NaN,NaN,Aluguel - Uso Instalações,NaN,556.162,0
27,NaN,NaN,NaN,NaN,NaN,NaN,157.668,132.480
28,Demonstrações dos Resultados,NaN,NaN,NaN,Depreciação,NaN,847.872,916.970
29,dos Períodos Findos em 31 de,NaN,NaN,NaN,Outros Custos,NaN,70.089,154.288
30,Dezembro de 2021 e 2020,NaN,NaN,NaN,SUPERAVIT OPERACIONAL BRUTO,NaN,43.544.348,36.437.790
31,NaN,NaN,Valores em Reais,NaN,DESPESAS OPERACIONAIS - MATRIZ,32,29.097.548,28.043.596
32,PASSIVO + PATRIMÔNIO LÍQUIDO,NOTA,NaN,NaN,Administrativas,NaN,19.797.994,20.047.924
33,RECEITAS OPERACIONAIS,28,309.247.648 277.049.558,NaN,Outras Despesas e Receitas Operacionais,NaN,7.850.935,6.766.968
34,RECEITAS MATRIZ,NaN,308.914.518 276.876.038,NaN,Depreciação,NaN,1.448.619,1.576.599
35,Receitas com Restrição,28a,215.616.477 214.121.450,NaN,(-) Recuperação de Despesas,NaN,0,-347.895
36,Convênio SUS - Internamento,NaN,139.365.739 144.261.146,NaN,DESPESAS OPERACIONAIS - FILIAL CURITIBA,33,-,0
37,Convênio SUS - Ambulatório,NaN,34.373.105 35.092.619,NaN,Administrativas,NaN,0,0
38,Convênio SUS - Radiotererapia e Quimioterapia,NaN,16.594.209 16.519.506,NaN,RESULTADO FINANCEIRO LÍQUIDO - MATRIZ,34,-1.234.408,-1.193.706
39,Convênio SUS - IAC,NaN,8.141.690 8.141.690,NaN,Receitas Financeiras,NaN,1.739.178,877.578
40,Convênio SUS - IAM Portaria no 1287,NaN,4.180.000 4.940.000,NaN,(-) Despesas Financeiras,NaN,-2.973.586,-2.071.284
41,Convênio Hosp. SUS,NaN,0 0,NaN,Correção Divida do PROSUS,NaN,0,0
42,SUS- APAC Hemodiálise,NaN,0 0,NaN,RESULTADO FINANC. LÍQ. FILIAL CURITBA,35,-36.799,-33.766
43,SUS- APAC Oftalmologia,NaN,0 0,NaN,(-) Despesas Financeiras,NaN,-36.799,-33.766
44,SUS- Incentivo AVC,NaN,1.085.498 1.085.498,NaN,RESULTADO OPERACIONAL,NaN,13.175.593,7.166.722
45,SUS- Incentivo NEO,NaN,949.964 949.866,NaN,SUPERAVIT DO PERÍODO,36,13.175.593,7.166.722

,14,Convênios Privados,Unnamed: 0,10.305.533,6.011.318,15
0,NaN,Pacientes Particulares,NaN,40.976.493,34.420.287,NaN
1,NaN,Doações Recebidas,NaN,2.282.808,1.927.002,NaN
2,NaN,Remissão de Dividas do PROSUS,NaN,29.284.467,15.008.710,NaN
3,NaN,Receitas Diversas,NaN,10.337.495,4.688.381,NaN
4,NaN,RECEITAS FILIAL CURITIBA,NaN,333.130,173.520,NaN
5,NaN,Receitas sem Restrição,28b,333.130,173.520,NaN
6,NaN,Convênios Privados,NaN,248.565,151.463,NaN
7,NaN,Pacientes Particulares,NaN,84.565,22.057,NaN
8,NaN,DEDUÇÕES DAS RECEITAS,29,-1.034.212,-3.481.921,NaN
9,NaN,(-) Devolução p/ Pacientes,NaN,-7.961,-2.700,NaN
10,NaN,(-) Glosas s/ Serviços,NaN,-1.026.251,-3.479.221,NaN
11,NaN,RECEITA OPERACIONAL LÍQUIDA,NaN,308.213.436,273.567.637,NaN
12,NaN,CUSTOS DOS SERV./PRODUTOS - MATRIZ,30,262.204.797,235.215.933,NaN
13,NaN,Custo com Pessoal,NaN,82.167.977,71.082.565,NaN
14,NaN,Suprimentos,NaN,56.625.339,44.342.432,NaN
15,NaN,Aluguel - Uso Instalações,NaN,6.003.872,59.092,NaN
16,NaN,NaN,NaN,95.813.647,97.435.610,NaN
17,NaN,Depreciação,NaN,12.231.182,12.769.719,NaN
18,NaN,Outros Custos,NaN,9.362.780,9.526.515,NaN
19,NaN,CUSTOS SERV./PROD - FILIAL DE CURITIBA,31,2.464.291,1.913.914,NaN
20,NaN,Custo com Pessoal,NaN,832.500,710.176,NaN
21,NaN,Aluguel - Uso Instalações,NaN,556.162,0,NaN
22,NaN,NaN,NaN,157.668,132.480,NaN
23,NaN,Depreciação,NaN,847.872,916.970,NaN
24,NaN,Outros Custos,NaN,70.089,154.288,NaN
25,NaN,SUPERAVIT OPERACIONAL BRUTO,NaN,43.544.348,36.437.790,NaN
26,NaN,DESPESAS OPERACIONAIS - MATRIZ,32,29.097.548,28.043.596,NaN
27,NaN,Administrativas,NaN,19.797.994,20.047.924,NaN
28,NaN,Outras Despesas e Receitas Operacionais,NaN,7.850.935,6.766.968,NaN
29,NaN,Depreciação,NaN,1.448.619,1.576.599,NaN
30,NaN,(-) Recuperação de Despesas,NaN,0,-347.895,NaN
31,NaN,DESPESAS OPERACIONAIS - FILIAL CURITIBA,33,-,0,NaN
32,NaN,Administrativas,NaN,0,0,NaN
33,NaN,RESULTADO FINANCEIRO LÍQUIDO - MATRIZ,34,-1.234.408,-1.193.706,NaN
34,NaN,Receitas Financeiras,NaN,1.739.178,877.578,NaN
35,NaN,(-) Despesas Financeiras,NaN,-2.973.586,-2.071.284,NaN
36,NaN,Correção Divida do PROSUS,NaN,0,0,NaN
37,NaN,RESULTADO FINANC. LÍQ. FILIAL CURITBA,35,-36.799,-33.766,NaN
38,NaN,(-) Despesas Financeiras,NaN,-36.799,-33.766,NaN

In [6]:
## SEPARANDO AS DUAS TABELAS DA TABELA SELECIONADA

tabelas = lista_tabelas[0]

## Selecionando as linhas que nós queremos apenas (no caso a primeira tabela estava entre as linhas de indice 0 e 25)
tabela = tabelas[0:25]

## Para separar as colunas da outra tabela, realizei um drop para separá-los
tabela = tabela.drop(columns = ["Unnamed: 1", 'SUS- Incentivo - Diárias Extras de UTI', 'Unnamed: 2', '9.959', '136.865'], axis = 1)

## Nessa tabela tinhamos duas colunas de ano com os valores, então realizei o split para poder separá-las
tabela[['2021', '2022']] = tabela["Unnamed: 0"].str.split(" ", expand=True)

## Retirei a coluna vazia que não tinha puxado os valores
tabela = tabela.drop("Unnamed: 0", axis = 1)

display(tabela)

,PASSIVO + PATRIMÔNIO LÍQUIDO,NOTA,2021,2022
0,CIRCULANTE,NaN,73.108.189,41.657.722
1,Fornecedores,NaN,12.559.112,9.301.363
2,Salários e Contribuições Sociais,NaN,15.156.339,11.716.560
3,Obrigações Fiscais,NaN,411.790,1.296.084
4,Outras Obrigações,NaN,1.363.500,1.569.931
5,Créditos de Clientes,NaN,400.445,472.619
6,NaN,NaN,23.284.719,1.279.161
7,Emprestimos e Financiamentos de Ativos,NaN,0,2.651.925
8,Passivo de Arrendamento,NaN,9.106.138,6.596.923
9,Receitas Diferidas - Subvenção a Realizar,NaN,10.826.146,6.773.156
10,NÃOC IRCULANTE,NaN,95.010.439,124.687.325
11,Emprestimos e Financiamentos de Ativos,NaN,106.054,106.054
12,NaN,NaN,428.571,300.057
13,Passivo de Arrendamento,NaN,0,2.173.487
14,Receitas Diferidas - Subvenções a Realizar,NaN,38.138.139,36.698.692
15,Provisão Para Contingências,NaN,3.277.226,3.064.119
16,Dívida Tributária - Prosus - Lei no 12.873/13,NaN,49.196.083,78.480.550
17,Créditos Não Homologados -,NaN,3.864.366,3.864.366
18,Prosus - Lei no 12.873/13,NaN,NaN,NaN
19,PATRIMÔNIO LÍQUIDO,NaN,17.161.647,3.926.972
20,Patrimonio Social,NaN,62.185.996,62.185.996
21,Reservas de Contribuição,NaN,816.784,816.784
22,NaN,NaN,-59.016.726,-66.242.530
23,Superávit do Exercício,NaN,13.175.593,7.166.722
24,TOTAL PASSIVO + PATRIMÔNIO LÍQUIDO,NaN,185.280.274,170.272.019

In [ ]:
## Primeira Tabela salva em xlsx
tabela.to_excel("Tabelas.xlsx")

In [9]:
# Realizei uma nova leitura do arquivo (para pegarmos ele no formato original)

lista_tabelas = tabula.read_pdf("https://hospitalangelinacaron.org.br/hac/wp-content/uploads/2022/12/Balanco-Social-2021.pdf", pages='8')
print(len(lista_tabelas))

WARNING:tabula.io:Got stderr: Aug 07, 2023 11:41:07 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (31) in font KHJFJO+Montserrat-Light
Aug 07, 2023 11:41:08 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 31 (.notdef) in font KHJFJO+Montserrat-Light

2

In [11]:
# Creio que não havia mencionado mas as tabelas com o tabula são convertidas em listas de tabelas, as quais precisam
# dessa loop `for` para a visualização

for tabela in lista_tabelas:
  display(tabela)

,PASSIVO + PATRIMÔNIO LÍQUIDO,NOTA,Unnamed: 0,Unnamed: 1,SUS- Incentivo - Diárias Extras de UTI,Unnamed: 2,9.959,136.865
0,CIRCULANTE,NaN,73.108.189 41.657.722,NaN,Receitas a Faturar,NaN,6.067.487,0
1,Fornecedores,NaN,12.559.112 9.301.363,NaN,Subvenções Recebidas,NaN,4.848.826,2.994.260
2,Salários e Contribuições Sociais,NaN,15.156.339 11.716.560,NaN,Receitas sem Restrição,28b,93.298.042,62.754.588
3,Obrigações Fiscais,NaN,411.790 1.296.084,NaN,Convênios Assistenciais,NaN,111.246,698.890
4,Outras Obrigações,NaN,1.363.500 1.569.931,NaN,Convênios Privados,NaN,10.305.533,6.011.318
5,Créditos de Clientes,NaN,400.445 472.619,NaN,Pacientes Particulares,NaN,40.976.493,34.420.287
6,NaN,NaN,23.284.719 1.279.161,NaN,Doações Recebidas,NaN,2.282.808,1.927.002
7,Emprestimos e Financiamentos de Ativos,NaN,0 2.651.925,NaN,Remissão de Dividas do PROSUS,NaN,29.284.467,15.008.710
8,Passivo de Arrendamento,NaN,9.106.138 6.596.923,NaN,Receitas Diversas,NaN,10.337.495,4.688.381
9,Receitas Diferidas - Subvenção a Realizar,NaN,10.826.146 6.773.156,NaN,RECEITAS FILIAL CURITIBA,NaN,333.130,173.520
10,NÃOC IRCULANTE,NaN,95.010.439 124.687.325,NaN,Receitas sem Restrição,28b,333.130,173.520
11,Emprestimos e Financiamentos de Ativos,NaN,106.054 106.054,NaN,Convênios Privados,NaN,248.565,151.463
12,NaN,NaN,428.571 300.057,NaN,Pacientes Particulares,NaN,84.565,22.057
13,Passivo de Arrendamento,NaN,0 2.173.487,NaN,DEDUÇÕES DAS RECEITAS,29,-1.034.212,-3.481.921
14,Receitas Diferidas - Subvenções a Realizar,NaN,38.138.139 36.698.692,NaN,(-) Devolução p/ Pacientes,NaN,-7.961,-2.700
15,Provisão Para Contingências,NaN,3.277.226 3.064.119,NaN,(-) Glosas s/ Serviços,NaN,-1.026.251,-3.479.221
16,Dívida Tributária - Prosus - Lei no 12.873/13,NaN,49.196.083 78.480.550,NaN,RECEITA OPERACIONAL LÍQUIDA,NaN,308.213.436,273.567.637
17,Créditos Não Homologados -,NaN,3.864.366 3.864.366,NaN,CUSTOS DOS SERV./PRODUTOS - MATRIZ,30,262.204.797,235.215.933
18,Prosus - Lei no 12.873/13,NaN,NaN,NaN,Custo com Pessoal,NaN,82.167.977,71.082.565
19,PATRIMÔNIO LÍQUIDO,NaN,17.161.647 3.926.972,NaN,Suprimentos,NaN,56.625.339,44.342.432
20,Patrimonio Social,NaN,62.185.996 62.185.996,NaN,Aluguel - Uso Instalações,NaN,6.003.872,59.092
21,Reservas de Contribuição,NaN,816.784 816.784,NaN,NaN,NaN,95.813.647,97.435.610
22,NaN,NaN,-59.016.726 -66.242.530,NaN,Depreciação,NaN,12.231.182,12.769.719
23,Superávit do Exercício,NaN,13.175.593 7.166.722,NaN,Outros Custos,NaN,9.362.780,9.526.515
24,TOTAL PASSIVO + PATRIMÔNIO LÍQUIDO,NaN,185.280.274 170.272.019,NaN,CUSTOS SERV./PROD - FILIAL DE CURITIBA,31,2.464.291,1.913.914
25,NaN,NaN,NaN,NaN,Custo com Pessoal,NaN,832.500,710.176
26,NaN,NaN,NaN,NaN,Aluguel - Uso Instalações,NaN,556.162,0
27,NaN,NaN,NaN,NaN,NaN,NaN,157.668,132.480
28,Demonstrações dos Resultados,NaN,NaN,NaN,Depreciação,NaN,847.872,916.970
29,dos Períodos Findos em 31 de,NaN,NaN,NaN,Outros Custos,NaN,70.089,154.288
30,Dezembro de 2021 e 2020,NaN,NaN,NaN,SUPERAVIT OPERACIONAL BRUTO,NaN,43.544.348,36.437.790
31,NaN,NaN,Valores em Reais,NaN,DESPESAS OPERACIONAIS - MATRIZ,32,29.097.548,28.043.596
32,PASSIVO + PATRIMÔNIO LÍQUIDO,NOTA,NaN,NaN,Administrativas,NaN,19.797.994,20.047.924
33,RECEITAS OPERACIONAIS,28,309.247.648 277.049.558,NaN,Outras Despesas e Receitas Operacionais,NaN,7.850.935,6.766.968
34,RECEITAS MATRIZ,NaN,308.914.518 276.876.038,NaN,Depreciação,NaN,1.448.619,1.576.599
35,Receitas com Restrição,28a,215.616.477 214.121.450,NaN,(-) Recuperação de Despesas,NaN,0,-347.895
36,Convênio SUS - Internamento,NaN,139.365.739 144.261.146,NaN,DESPESAS OPERACIONAIS - FILIAL CURITIBA,33,-,0
37,Convênio SUS - Ambulatório,NaN,34.373.105 35.092.619,NaN,Administrativas,NaN,0,0
38,Convênio SUS - Radiotererapia e Quimioterapia,NaN,16.594.209 16.519.506,NaN,RESULTADO FINANCEIRO LÍQUIDO - MATRIZ,34,-1.234.408,-1.193.706
39,Convênio SUS - IAC,NaN,8.141.690 8.141.690,NaN,Receitas Financeiras,NaN,1.739.178,877.578
40,Convênio SUS - IAM Portaria no 1287,NaN,4.180.000 4.940.000,NaN,(-) Despesas Financeiras,NaN,-2.973.586,-2.071.284
41,Convênio Hosp. SUS,NaN,0 0,NaN,Correção Divida do PROSUS,NaN,0,0
42,SUS- APAC Hemodiálise,NaN,0 0,NaN,RESULTADO FINANC. LÍQ. FILIAL CURITBA,35,-36.799,-33.766
43,SUS- APAC Oftalmologia,NaN,0 0,NaN,(-) Despesas Financeiras,NaN,-36.799,-33.766
44,SUS- Incentivo AVC,NaN,1.085.498 1.085.498,NaN,RESULTADO OPERACIONAL,NaN,13.175.593,7.166.722
45,SUS- Incentivo NEO,NaN,949.964 949.866,NaN,SUPERAVIT DO PERÍODO,36,13.175.593,7.166.722

,14,Convênios Privados,Unnamed: 0,10.305.533,6.011.318,15
0,NaN,Pacientes Particulares,NaN,40.976.493,34.420.287,NaN
1,NaN,Doações Recebidas,NaN,2.282.808,1.927.002,NaN
2,NaN,Remissão de Dividas do PROSUS,NaN,29.284.467,15.008.710,NaN
3,NaN,Receitas Diversas,NaN,10.337.495,4.688.381,NaN
4,NaN,RECEITAS FILIAL CURITIBA,NaN,333.130,173.520,NaN
5,NaN,Receitas sem Restrição,28b,333.130,173.520,NaN
6,NaN,Convênios Privados,NaN,248.565,151.463,NaN
7,NaN,Pacientes Particulares,NaN,84.565,22.057,NaN
8,NaN,DEDUÇÕES DAS RECEITAS,29,-1.034.212,-3.481.921,NaN
9,NaN,(-) Devolução p/ Pacientes,NaN,-7.961,-2.700,NaN
10,NaN,(-) Glosas s/ Serviços,NaN,-1.026.251,-3.479.221,NaN
11,NaN,RECEITA OPERACIONAL LÍQUIDA,NaN,308.213.436,273.567.637,NaN
12,NaN,CUSTOS DOS SERV./PRODUTOS - MATRIZ,30,262.204.797,235.215.933,NaN
13,NaN,Custo com Pessoal,NaN,82.167.977,71.082.565,NaN
14,NaN,Suprimentos,NaN,56.625.339,44.342.432,NaN
15,NaN,Aluguel - Uso Instalações,NaN,6.003.872,59.092,NaN
16,NaN,NaN,NaN,95.813.647,97.435.610,NaN
17,NaN,Depreciação,NaN,12.231.182,12.769.719,NaN
18,NaN,Outros Custos,NaN,9.362.780,9.526.515,NaN
19,NaN,CUSTOS SERV./PROD - FILIAL DE CURITIBA,31,2.464.291,1.913.914,NaN
20,NaN,Custo com Pessoal,NaN,832.500,710.176,NaN
21,NaN,Aluguel - Uso Instalações,NaN,556.162,0,NaN
22,NaN,NaN,NaN,157.668,132.480,NaN
23,NaN,Depreciação,NaN,847.872,916.970,NaN
24,NaN,Outros Custos,NaN,70.089,154.288,NaN
25,NaN,SUPERAVIT OPERACIONAL BRUTO,NaN,43.544.348,36.437.790,NaN
26,NaN,DESPESAS OPERACIONAIS - MATRIZ,32,29.097.548,28.043.596,NaN
27,NaN,Administrativas,NaN,19.797.994,20.047.924,NaN
28,NaN,Outras Despesas e Receitas Operacionais,NaN,7.850.935,6.766.968,NaN
29,NaN,Depreciação,NaN,1.448.619,1.576.599,NaN
30,NaN,(-) Recuperação de Despesas,NaN,0,-347.895,NaN
31,NaN,DESPESAS OPERACIONAIS - FILIAL CURITIBA,33,-,0,NaN
32,NaN,Administrativas,NaN,0,0,NaN
33,NaN,RESULTADO FINANCEIRO LÍQUIDO - MATRIZ,34,-1.234.408,-1.193.706,NaN
34,NaN,Receitas Financeiras,NaN,1.739.178,877.578,NaN
35,NaN,(-) Despesas Financeiras,NaN,-2.973.586,-2.071.284,NaN
36,NaN,Correção Divida do PROSUS,NaN,0,0,NaN
37,NaN,RESULTADO FINANC. LÍQ. FILIAL CURITBA,35,-36.799,-33.766,NaN
38,NaN,(-) Despesas Financeiras,NaN,-36.799,-33.766,NaN

In [12]:
## SEPARANDO AS DUAS TABELAS DA TABELA SELECIONADA

tabelas = lista_tabelas[0]

# A primeira parte da segunda tabela encontrava-se entre os indices 32 e 46
tabela = tabelas[32:46]

# Retiramos as colunas que faziam parte da primeira tabela.
tabela = tabela.drop(columns = ["Unnamed: 1", 'SUS- Incentivo - Diárias Extras de UTI', 'Unnamed: 2', '9.959', '136.865'], axis = 1)

# Realizamos o mesmo processo de split dos valores
tabela[['2021', '2022']] = tabela["Unnamed: 0"].str.split(" ", expand=True)

# Retiramos a coluna que não nos interessa
tabela = tabela.drop("Unnamed: 0", axis = 1)


display(tabela)

,PASSIVO + PATRIMÔNIO LÍQUIDO,NOTA,2021,2022
32,PASSIVO + PATRIMÔNIO LÍQUIDO,NOTA,NaN,NaN
33,RECEITAS OPERACIONAIS,28,309.247.648,277.049.558
34,RECEITAS MATRIZ,NaN,308.914.518,276.876.038
35,Receitas com Restrição,28a,215.616.477,214.121.450
36,Convênio SUS - Internamento,NaN,139.365.739,144.261.146
37,Convênio SUS - Ambulatório,NaN,34.373.105,35.092.619
38,Convênio SUS - Radiotererapia e Quimioterapia,NaN,16.594.209,16.519.506
39,Convênio SUS - IAC,NaN,8.141.690,8.141.690
40,Convênio SUS - IAM Portaria no 1287,NaN,4.180.000,4.940.000
41,Convênio Hosp. SUS,NaN,0,0
42,SUS- APAC Hemodiálise,NaN,0,0
43,SUS- APAC Oftalmologia,NaN,0,0
44,SUS- Incentivo AVC,NaN,1.085.498,1.085.498
45,SUS- Incentivo NEO,NaN,949.964,949.866

In [ ]:
tabela.to_excel("Continuação.xlsx")

In [13]:
# Nova leitura
lista_tabelas3 = tabula.read_pdf("https://hospitalangelinacaron.org.br/hac/wp-content/uploads/2022/12/Balanco-Social-2021.pdf", pages='8')

WARNING:tabula.io:Got stderr: Aug 07, 2023 11:43:52 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (31) in font KHJFJO+Montserrat-Light
Aug 07, 2023 11:43:54 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 31 (.notdef) in font KHJFJO+Montserrat-Light

In [14]:
## SEPARANDO AS DUAS TABELAS DA TABELA SELECIONADA

tabelas = lista_tabelas[0]
# Nessa a separação das colunas foi um pouco diferente. Utilizando o método `.iloc` seleciono todos os valores dos índices que precisava
# Posteriormente realizo o tratamento relacionado nessas 4 colunas

tabelas = tabelas.iloc[:, 4:8]
display(tabelas)

,SUS- Incentivo - Diárias Extras de UTI,Unnamed: 2,9.959,136.865
0,Receitas a Faturar,NaN,6.067.487,0
1,Subvenções Recebidas,NaN,4.848.826,2.994.260
2,Receitas sem Restrição,28b,93.298.042,62.754.588
3,Convênios Assistenciais,NaN,111.246,698.890
4,Convênios Privados,NaN,10.305.533,6.011.318
5,Pacientes Particulares,NaN,40.976.493,34.420.287
6,Doações Recebidas,NaN,2.282.808,1.927.002
7,Remissão de Dividas do PROSUS,NaN,29.284.467,15.008.710
8,Receitas Diversas,NaN,10.337.495,4.688.381
9,RECEITAS FILIAL CURITIBA,NaN,333.130,173.520
10,Receitas sem Restrição,28b,333.130,173.520
11,Convênios Privados,NaN,248.565,151.463
12,Pacientes Particulares,NaN,84.565,22.057
13,DEDUÇÕES DAS RECEITAS,29,-1.034.212,-3.481.921
14,(-) Devolução p/ Pacientes,NaN,-7.961,-2.700
15,(-) Glosas s/ Serviços,NaN,-1.026.251,-3.479.221
16,RECEITA OPERACIONAL LÍQUIDA,NaN,308.213.436,273.567.637
17,CUSTOS DOS SERV./PRODUTOS - MATRIZ,30,262.204.797,235.215.933
18,Custo com Pessoal,NaN,82.167.977,71.082.565
19,Suprimentos,NaN,56.625.339,44.342.432
20,Aluguel - Uso Instalações,NaN,6.003.872,59.092
21,NaN,NaN,95.813.647,97.435.610
22,Depreciação,NaN,12.231.182,12.769.719
23,Outros Custos,NaN,9.362.780,9.526.515
24,CUSTOS SERV./PROD - FILIAL DE CURITIBA,31,2.464.291,1.913.914
25,Custo com Pessoal,NaN,832.500,710.176
26,Aluguel - Uso Instalações,NaN,556.162,0
27,NaN,NaN,157.668,132.480
28,Depreciação,NaN,847.872,916.970
29,Outros Custos,NaN,70.089,154.288
30,SUPERAVIT OPERACIONAL BRUTO,NaN,43.544.348,36.437.790
31,DESPESAS OPERACIONAIS - MATRIZ,32,29.097.548,28.043.596
32,Administrativas,NaN,19.797.994,20.047.924
33,Outras Despesas e Receitas Operacionais,NaN,7.850.935,6.766.968
34,Depreciação,NaN,1.448.619,1.576.599
35,(-) Recuperação de Despesas,NaN,0,-347.895
36,DESPESAS OPERACIONAIS - FILIAL CURITIBA,33,-,0
37,Administrativas,NaN,0,0
38,RESULTADO FINANCEIRO LÍQUIDO - MATRIZ,34,-1.234.408,-1.193.706
39,Receitas Financeiras,NaN,1.739.178,877.578
40,(-) Despesas Financeiras,NaN,-2.973.586,-2.071.284
41,Correção Divida do PROSUS,NaN,0,0
42,RESULTADO FINANC. LÍQ. FILIAL CURITBA,35,-36.799,-33.766
43,(-) Despesas Financeiras,NaN,-36.799,-33.766
44,RESULTADO OPERACIONAL,NaN,13.175.593,7.166.722
45,SUPERAVIT DO PERÍODO,36,13.175.593,7.166.722

In [ ]:
tabelas.to_excel("terceira_parte.xlsx")